name: Code Review

permissions:
  contents: read
  pull-requests: write
  models: read

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: windows
    steps:
      - uses: sch2015/CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          USE_GITHUB_MODELS: false
          LOG_LEVEL: debug
          INCLUDE_PATTERNS: src/*,.github/**/*

          OPENAI_API_KEY: 123
          OPENAI_API_ENDPOINT: http://192.168.3.250:8963/v1
          MODEL: deepseek-coder:6.7b
          LANGUAGE: Chinese
          IGNORE_PATTERNS: /node_modules/**/*,*.md
